spring.application.name=E-connect-backend
server.port=8080
spring.data.mongodb.uri=mongodb+srv://pamith552_db_user:nS29tTpnx6P8IG9t@cluster0.xxxbahy.mongodb.net/E-connect?appName=Cluster0
logging.level.com.ecoconnect=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
server.error.include-message=always
server.error.include-binding-errors=always
